apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devhuddle-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.devhuddle.online
    secretName: devhuddle-tls
  rules:
  - host: api.devhuddle.online
    http:
      paths:
      - path: /api(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
