apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: media-service
        image: ghcr.io/junaidchm/media-service:latest
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: devhuddle-config
        - secretRef:
            name: devhuddle-secrets
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: devhuddle-secrets
              key: MEDIA_DATABASE_URL
        - name: R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: devhuddle-secrets
              key: R2_ACCESS_KEY_ID
        - name: R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: devhuddle-secrets
              key: R2_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-service
  ports:
  - port: 5003
    targetPort: 5003
